//go:build ignore

package main

import (
	"go/format"
	"log"
	"os"
)

func main() {
	const source = `// Code generated by mini-cloud mockgen; DO NOT EDIT.

package server

import (
	"io"

	"mini-cloud/internal/models"
)

type mockFileStore struct {
	saveFunc   func(id string, r io.Reader) error
	getFunc    func(id string) (io.ReadCloser, error)
	deleteFunc func(id string) error
	listFunc   func() ([]string, error)
}

func (m mockFileStore) Save(id string, r io.Reader) error {
	return m.saveFunc(id, r)
}

func (m mockFileStore) Get(id string) (io.ReadCloser, error) {
	return m.getFunc(id)
}

func (m mockFileStore) Delete(id string) error {
	return m.deleteFunc(id)
}

func (m mockFileStore) List() ([]string, error) {
	return m.listFunc()
}

type mockCollectionService struct {
	listFunc       func() ([]models.FileCollection, error)
	createFunc     func(name string, fileIDs []models.FileID) (models.FileCollection, error)
	getFunc        func(id models.CollectionID) (models.FileCollection, error)
	addFileFunc    func(collectionID models.CollectionID, fileID models.FileID) (models.FileCollection, error)
	removeFileFunc func(collectionID models.CollectionID, fileID models.FileID) (models.FileCollection, error)
	deleteFunc     func(id models.CollectionID) error
}

func (m mockCollectionService) List() ([]models.FileCollection, error) {
	return m.listFunc()
}

func (m mockCollectionService) Create(name string, fileIDs []models.FileID) (models.FileCollection, error) {
	return m.createFunc(name, fileIDs)
}

func (m mockCollectionService) Get(id models.CollectionID) (models.FileCollection, error) {
	return m.getFunc(id)
}

func (m mockCollectionService) AddFile(collectionID models.CollectionID, fileID models.FileID) (models.FileCollection, error) {
	return m.addFileFunc(collectionID, fileID)
}

func (m mockCollectionService) RemoveFile(collectionID models.CollectionID, fileID models.FileID) (models.FileCollection, error) {
	return m.removeFileFunc(collectionID, fileID)
}

func (m mockCollectionService) Delete(id models.CollectionID) error {
	return m.deleteFunc(id)
}
`

	formatted, err := format.Source([]byte(source))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("mocks_test.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
}
